version: '3.8'
services:
  application:
    image: todo:0.0.1
    healthcheck:
      test: "curl -f localhost:8080"
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knative_demo
      - HEALTH-CHECK=<<application-checks.heart-beat-check>>
      - CONSCIOUS-CHECK=<<application-checks.conscious-check>>
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db-init-scripts/postgres:/docker-entrypoint-initdb.d
  mongo:
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:4.2.24
volumes:
  postgres:
    driver: local